-- /ami/exchange/startup.lua
-- The Great Ami Exchange v1.0 — entry point.
-- Trimmed from /ami/shop/startup.lua. Run: shell.run("/ami/exchange/startup")
--
-- Players walk up to this computer's terminal:
--   [B] Buy coins  — pay AMI through a wallet invoice, get /coins
--   [S] Sell coins — coins are taken with the command block, AMI is sent
--
-- Peripherals (see exchange_api.lua): modem on BACK, optional monitor on TOP,
-- and a command block on any side.
--
-- SECURITY: this computer can run server commands. Players must only be able
-- to right-click it — never break it, place blocks next to the command block,
-- or reach a shell. Ctrl+T is disabled below and admin functions sit behind
-- the hidden backtick (`) key + password; the build itself must be protected
-- (claimed chunk / spawn protection).

package.path = package.path .. ";/ami/exchange/?.lua"

-- Ctrl+T must not drop a player into a shell next to a command block.
os.pullEvent = os.pullEventRaw

local api = require("exchange_api")
local ui  = require("exchange_ui")

local SYNC_INTERVAL = 30   -- seconds between reserve refreshes
local POLL_INTERVAL = 4    -- seconds between payment checks while waiting
local SHOP_CHANNEL  = 1338
local REPO_BASE     = "https://raw.githubusercontent.com/Teru-dot-png/amicoin-fullpower/refs/heads/main"

local UPDATE_FILES = {
    { src = "/shared/xtea.lua",                dst = "/shared/xtea.lua"                },
    { src = "/ami/exchange/exchange_api.lua",  dst = "/ami/exchange/exchange_api.lua"  },
    { src = "/ami/exchange/exchange_ui.lua",   dst = "/ami/exchange/exchange_ui.lua"   },
    { src = "/ami/exchange/startup.lua",       dst = "/ami/exchange/startup.lua"       },
}

-- ── Config helpers ────────────────────────────────────────────────────────────
local function loadCfg()   return api.loadConfig() end
local function saveCfg(c)  api.saveConfig(c) end

-- ── Lock-down ─────────────────────────────────────────────────────────────────
-- A reboot (Ctrl+R) must come straight back here, and a floppy placed next to
-- the computer must not be able to run its own startup.
local function lockDown()
    settings.set("shell.allow_disk_startup", false)
    settings.save()
    if not fs.exists("/startup.lua") then
        local f = fs.open("/startup.lua", "w")
        f.write("-- Auto-generated by /ami/exchange/startup.lua\n")
        f.write('shell.run("/ami/exchange/startup")\n')
        f.close()
    end
end

-- ── FNV-1a hash (for self-update fingerprint verification) ───────────────────
local function fnv1a(s)
    local hash = 2166136261
    for i = 1, #s do
        hash = bit32.bxor(hash, string.byte(s, i))
        hash = (hash * 16777619) % 4294967296
    end
    return string.format("%08x", hash)
end

-- ── Self-update ───────────────────────────────────────────────────────────────
local function selfUpdate()
    term.clear(); term.setCursorPos(1, 1)
    term.setTextColor(colors.yellow)
    print("Ami Exchange Self-Update")
    print("Downloading from GitHub...")
    print("")
    term.setTextColor(colors.white)

    -- Delta-check helper: hash a file on disk, nil if absent.
    local function hashFile(path)
        if not fs.exists(path) then return nil end
        local f = fs.open(path, "r")
        local c = f.readAll(); f.close()
        return fnv1a(c)
    end
    local failed = false
    local hashes = {}

    for _, entry in ipairs(UPDATE_FILES) do
        io.write("  " .. entry.dst .. " ... ")
        local res = http.get(REPO_BASE .. entry.src)
        if not res then
            term.setTextColor(colors.red)
            print("FAILED (no response)")
            term.setTextColor(colors.white)
            failed = true
        else
            local content = res.readAll(); res.close()
            if #content < 64 then
                term.setTextColor(colors.red)
                print("FAILED (too short — 404?)")
                term.setTextColor(colors.white)
                failed = true
            else
                local remoteHash = fnv1a(content)
                if hashFile(entry.dst) == remoteHash then
                    term.setTextColor(colors.gray)
                    print("skip  [" .. remoteHash .. "]")
                    term.setTextColor(colors.white)
                    hashes[#hashes + 1] = remoteHash
                else
                    local bakPath = entry.dst .. ".bak"
                    if fs.exists(entry.dst) then
                        if fs.exists(bakPath) then fs.delete(bakPath) end
                        pcall(fs.copy, entry.dst, bakPath)
                    end
                    local f = fs.open(entry.dst, "w")
                    f.write(content); f.close()
                    if hashFile(entry.dst) ~= remoteHash then
                        if fs.exists(bakPath) then
                            pcall(fs.delete, entry.dst)
                            pcall(fs.copy, bakPath, entry.dst)
                        end
                        term.setTextColor(colors.red)
                        print("FAILED (verify -- backup restored)")
                        term.setTextColor(colors.white)
                        failed = true
                    else
                        term.setTextColor(colors.green)
                        print("OK  [" .. remoteHash .. "]")
                        term.setTextColor(colors.white)
                        hashes[#hashes + 1] = remoteHash
                    end
                end
            end
        end
    end

    print("")
    if failed then
        term.setTextColor(colors.red)
        print("Update failed. Backup files (.bak) retained.")
        print("The exchange will continue running the old version.")
        term.setTextColor(colors.white)
        os.sleep(3)
    else
        local combined = table.concat(hashes, ":")
        term.setTextColor(colors.green)
        print("Update complete!")
        term.setTextColor(colors.yellow)
        print("Fingerprint : " .. fnv1a(combined))
        term.setTextColor(colors.white)
        print("Rebooting in 3 seconds...")
        os.sleep(3)
        os.reboot()
    end
end

-- ── Terminal helpers ──────────────────────────────────────────────────────────
local function header(title)
    term.setBackgroundColor(colors.black)
    term.setCursorPos(1, 1); term.clear()
    term.setTextColor(colors.orange)
    print("  " .. title)
    term.setTextColor(colors.gray)
    print("  ----------------------------------------")
    term.setTextColor(colors.white)
end

local function say(color, text)
    term.setTextColor(color); print(text); term.setTextColor(colors.white)
end

local function ask(prompt)
    io.write(prompt)
    return ((io.read() or ""):gsub("^%s+", ""):gsub("%s+$", ""))
end

-- Menus read "char" events, not "key": a key press is followed by a char
-- event, and reacting to the key would leave that character to be typed into
-- the next prompt. Loops because Ctrl+T ("terminate") ignores the filter.
local function menuKey()
    while true do
        local ev, ch = os.pullEvent("char")
        if ev == "char" then return ch:lower() end
    end
end

local function anyKey()
    term.setTextColor(colors.gray)
    print("")
    print("  Press any key...")
    term.setTextColor(colors.white)
    os.pullEvent("key")
    os.sleep(0.1)   -- swallow the char event that follows the key
end

-- Short form used in the wallet's title bar: a1b2..c3d4
local function shortAddr(addr)
    return addr:sub(1, 4) .. ".." .. addr:sub(-4)
end

local lastStatus = nil   -- last trade line for the monitor

local function drawBoard()
    local cfg = loadCfg()
    local open, reason = api.isOpen()
    ui.draw({
        name    = cfg.shop_name,
        rate    = cfg.rate,
        reserve = api.getShopBal(),
        open    = open,
        reason  = reason,
        status  = lastStatus,
    })
end

-- ── Periodic reserve sync ─────────────────────────────────────────────────────
local function syncLoop()
    api.registerShop()
    api.witnessBalance()
    drawBoard()
    while true do
        os.sleep(SYNC_INTERVAL)
        api.witnessBalance()
        drawBoard()
    end
end

-- ── Public menu ───────────────────────────────────────────────────────────────
-- Admin access: hidden backtick (`) key -- never shown in this menu.
local function printMenu()
    local cfg = loadCfg()
    local open, reason = api.isOpen()
    header(cfg.shop_name)
    term.setTextColor(colors.yellow)
    print(string.format("  1 coin = %d uAMI  (%.6f AMI)", cfg.rate, cfg.rate / 1000000))
    term.setTextColor(colors.lightGray)
    print(string.format("  Reserve: %.4f AMI", api.getShopBal() / 1000000))
    term.setTextColor(colors.white)
    print("")
    if open then
        print("  [B]  Buy coins   (pay AMI from your wallet)")
        print("  [S]  Sell coins  (get AMI in your wallet)")
        print("")
        term.setTextColor(colors.lightGray)
        print("  Stand next to the exchange and have your")
        print("  wallet pad with you.")
    else
        term.setTextColor(colors.red)
        print("  EXCHANGE CLOSED")
        print("  " .. (reason or ""))
    end
    term.setTextColor(colors.gray)
    print("  ----------------------------------------")
    term.setTextColor(colors.white)
end

-- Ask for the player's Minecraft name and their wallet address.
-- Returns name, addr — or nil after telling the player what went wrong.
local function askPlayer()
    local name = ask("  Your Minecraft name: ")
    if #name == 0 then return nil end
    if not api.validName(name) then
        say(colors.red, "  That is not a Minecraft name (letters, digits, _).")
        anyKey(); return nil
    end
    io.write("  Finding your wallet... ")
    local addr = api.lookupName(name)
    if not addr then
        say(colors.red, "not found.")
        print("  Open your wallet pad once so it registers the")
        print("  name '" .. name .. "', then try again.")
        anyKey(); return nil
    end
    print("OK")
    return name, addr
end

local function askCoins(verb)
    local cfg = loadCfg()
    local coins = api.parseCoins(ask(string.format("  Coins to %s (1-%d): ", verb, cfg.max_coins)))
    if not coins then
        say(colors.red, "  Enter a whole number in that range.")
        anyKey(); return nil
    end
    return coins
end

-- ── Buy coins (AMI -> coins) ──────────────────────────────────────────────────
-- Sends an invoice to the player's wallet and waits for the payment to land.
local function waitForPayment(txId)
    local poll = os.startTimer(POLL_INTERVAL)
    while true do
        local ev, p1, p2, _, p4 = os.pullEvent()
        local check, giveUp = false, nil
        if ev == "modem_message" and p2 == SHOP_CHANNEL then
            local pkt = api.processShopBroadcast(p4)
            if pkt and pkt.tx_id == txId then
                -- Brief pause to let the node propagate the balance update.
                os.sleep(0.8)
                check = true
            end
        elseif ev == "timer" and p1 == poll then
            check = true
        elseif ev == "key" and p1 == keys.c then
            check, giveUp = true, "Cancelled -- nothing was charged."
        end
        local inv = api.getPendingInvoice()
        if inv and os.epoch("utc") > inv.expires then
            check, giveUp = true, "Timed out -- nothing was charged."
        end
        if check then
            -- Always look at the ledger first, even when giving up: the
            -- player may have paid a moment before pressing [C].
            local state, msg = api.settleInvoice(txId)
            if state ~= "waiting" then return state == "done", msg end
            if giveUp then
                api.cancelInvoice()
                return false, giveUp
            end
            poll = os.startTimer(POLL_INTERVAL)
        end
    end
end

local function buyFlow()
    header("Buy coins  (AMI -> coins)")
    local name, addr = askPlayer()
    if not name then return end
    if not api.playerPresent(name) then
        say(colors.red, "  " .. name .. " is not standing at the exchange.")
        print("  Check the spelling and stand next to it.")
        anyKey(); return
    end
    local coins = askCoins("buy")
    if not coins then return end
    local total = coins * loadCfg().rate

    local txId, err = api.sendInvoice(addr, name, coins)
    if not txId then
        say(colors.red, "  Could not start: " .. (err or "?"))
        anyKey(); return
    end
    lastStatus = name .. " is buying " .. coins .. " coins"
    drawBoard()
    print("")
    say(colors.yellow, string.format("  Invoice sent: %d uAMI (%.6f AMI)", total, total / 1000000))
    print("  Accept it on your wallet pad with [Y].")
    say(colors.gray, "  [C] cancel")

    local ok, msg = waitForPayment(txId)
    print("")
    say(ok and colors.green or colors.red, "  " .. msg)
    lastStatus = ok and (name .. " bought " .. coins .. " coins") or nil
    api.witnessBalance()
    drawBoard()
    anyKey()
end

-- ── Sell coins (coins -> AMI) ─────────────────────────────────────────────────
local function sellFlow()
    header("Sell coins  (coins -> AMI)")
    local name, addr = askPlayer()
    if not name then return end
    if not api.playerAlone(name) then
        say(colors.red, "  Selling needs " .. name .. " to be ALONE at the")
        say(colors.red, "  exchange. Ask everyone else to step back.")
        anyKey(); return
    end
    local coins = askCoins("sell")
    if not coins then return end
    local payout = coins * loadCfg().rate

    print("")
    say(colors.yellow, string.format("  You give : %d coins", coins))
    say(colors.yellow, string.format("  You get  : %d uAMI (%.6f AMI)", payout, payout / 1000000))
    print("  Paid to wallet: " .. shortAddr(addr))
    say(colors.lightGray, "  (must match Addr: in your wallet's title bar)")
    print("")
    io.write("  Confirm? [Y/N] ")
    local key = menuKey()
    print("")
    if key ~= "y" then
        print("  Cancelled."); os.sleep(0.8); return
    end

    print("  Working...")
    local ok, msg = api.sellCoins(name, addr, coins)
    say(ok and colors.green or colors.red, "  " .. msg)
    lastStatus = ok and (name .. " sold " .. coins .. " coins") or nil
    drawBoard()
    anyKey()
end

-- ── Node manager (called only from adminLoop, never from public inputLoop) ───
local function nodeManager()
    while true do
        term.setCursorPos(1, 1); term.clear()
        term.setTextColor(colors.orange)
        print("=== Ami Exchange  Node Manager ===")
        term.setTextColor(colors.white)
        print("")
        local cfg = loadCfg()
        if #cfg.nodes == 0 then
            print("  (no nodes configured)")
        else
            for i, n in ipairs(cfg.nodes) do
                print(string.format("  [%d] %-16s  %s...", i, n.name, n.key:sub(1, 8)))
            end
        end
        print("")
        print("[A]dd  [D]elete  [P] Node key password  [B]ack")
        local k = menuKey()

        if k == "b" then
            break

        elseif k == "a" then
            term.setCursorPos(1, 1); term.clear()
            term.setTextColor(colors.orange); print("Add Node"); term.setTextColor(colors.white)
            print("")
            io.write("Node name: ")
            local nm = (io.read() or ""):gsub("^%s+", ""):gsub("%s+$", "")
            if #nm == 0 then nm = "Node " .. (#loadCfg().nodes + 1) end
            print("")
            print("  [1] Enter 32-char key manually")
            print("  [2] Fetch via setup password")
            local addKey
            while not addKey do
                local ak = menuKey()
                if ak == "1" then
                    io.write("Node key (32 hex): ")
                    local raw = (io.read() or ""):gsub("%s", ""):lower()
                    if #raw == 32 then
                        addKey = raw
                    else
                        term.setTextColor(colors.red); print("Must be exactly 32 hex chars.")
                        term.setTextColor(colors.white); os.sleep(1)
                    end
                    break
                elseif ak == "2" then
                    io.write("Node lookup password: ")
                    local pw = read("*")
                    pw = (pw or ""):gsub("%s", "")
                    if #pw == 0 then
                        print("Cancelled."); os.sleep(0.8)
                    else
                        -- pcall: returns  pcallOk, fn_ok, nodeKey, fn_err
                        -- api.fetchNodeKey returns: ok(bool), key(str|nil), err(str|nil)
                        local pcallOk, fnOk, nodeKey, fnErr = pcall(api.fetchNodeKey, pw)
                        if not pcallOk then
                            -- Lua-level error (fnOk holds the error message)
                            term.setTextColor(colors.red); print("Connection error.")
                            term.setTextColor(colors.white); os.sleep(2)
                        elseif fnOk and type(nodeKey) == "string" and #nodeKey == 32 then
                            addKey = nodeKey
                            term.setTextColor(colors.green); print("Key received.")
                            term.setTextColor(colors.white); os.sleep(0.5)
                        else
                            local errMsg = type(fnErr) == "string" and fnErr or "Connection timeout"
                            term.setTextColor(colors.red); print("Lookup failed: " .. errMsg)
                            term.setTextColor(colors.white); os.sleep(2)
                        end
                    end
                    break
                end
            end
            if addKey then
                local callOk, ok, err = pcall(api.addNode, nm, addKey)
                if callOk and ok then
                    term.setTextColor(colors.green); print("Node added: " .. nm)
                elseif callOk then
                    term.setTextColor(colors.red); print("Failed: " .. (err or "unknown error"))
                else
                    term.setTextColor(colors.red); print("Internal error — node not saved.")
                end
                term.setTextColor(colors.white); os.sleep(1)
            end

        elseif k == "d" then
            term.setCursorPos(1, 1); term.clear()
            print("Delete Node")
            io.write("Index to remove: ")
            local idx = tonumber(io.read())
            local ok, err = api.removeNode(idx)
            term.setTextColor(ok and colors.green or colors.red)
            print(ok and "Removed." or ("Error: " .. (err or "?")))
            term.setTextColor(colors.white); os.sleep(1)

        elseif k == "p" then
            term.setCursorPos(1, 1); term.clear()
            term.setTextColor(colors.orange); print("Node Setup Password"); term.setTextColor(colors.white)
            print("This password is shared with your AmiCoin node.")
            print("It is used to fetch a node key without typing 32 hex chars.")
            print("")
            if api.hasNodePass() then
                print("A node setup password is already saved.")
            else
                print("No node setup password saved yet.")
            end
            print("")
            io.write("New password (blank to clear): ")
            local pw1 = read("*")
            if #pw1 == 0 then
                api.setNodePass("")
                term.setTextColor(colors.yellow); print("Node setup password cleared.")
            elseif #pw1 < 4 then
                term.setTextColor(colors.red); print("Too short -- minimum 4 characters. Unchanged.")
            else
                io.write("Confirm: "); local pw2 = read("*")
                if pw1 == pw2 then
                    api.setNodePass(pw1)
                    term.setTextColor(colors.green); print("Node setup password saved.")
                else
                    term.setTextColor(colors.red); print("Passwords do not match. Unchanged.")
                end
            end
            term.setTextColor(colors.white); os.sleep(1)
        end
    end
    api.registerShop()
end

-- ── Safety test (admin) ───────────────────────────────────────────────────────
local function safetyTest()
    header("Safety test")
    print("  Checks that /coins works from the command block")
    print("  and REFUSES to take coins a player does not have.")
    print("  Trading stays closed until this passes.")
    print("")
    print("  Stand alone next to the exchange. It adds and")
    print("  removes 1 coin on your account, then tries to")
    print("  remove more than you own (that must fail).")
    print("")
    local name = ask("  Your Minecraft name: ")
    if not api.validName(name) then
        say(colors.red, "  Not a valid name. Aborted."); anyKey(); return
    end
    print("  Run  /coins get " .. name .. "  in chat first.")
    local balance = tonumber(ask("  Coins you hold right now: "))
    if not balance or balance < 0 or balance ~= math.floor(balance) then
        say(colors.red, "  Not a whole number. Aborted."); anyKey(); return
    end
    print("")
    local ok, report = api.safetyTest(name, balance)
    for _, r in ipairs(report) do
        say(r.ok and colors.green or colors.red,
            (r.ok and "  [OK]   " or "  [FAIL] ") .. r.text)
    end
    print("")
    if ok then
        say(colors.green, "  Passed. The exchange is open.")
    else
        say(colors.red, "  FAILED. The exchange stays closed.")
        print("  If the last line failed, re-check your balance")
        print("  with /coins get -- coins were put back.")
    end
    drawBoard()
    anyKey()
end

local function showLog()
    header("Last log lines")
    local path = api.getLogFile()
    if not fs.exists(path) then
        print("  (log is empty)")
    else
        local lines = {}
        local f = fs.open(path, "r")
        for line in f.readLine do lines[#lines + 1] = line end
        f.close()
        local _, h = term.getSize()
        for i = math.max(1, #lines - (h - 6)), #lines do
            local line = lines[i]:gsub("^%[%d+%] ", "")
            term.setTextColor(line:find("ERROR", 1, true) and colors.red or colors.white)
            print(line:sub(1, 51))
        end
    end
    anyKey()
end

-- ── Admin panel loop (called from inputLoop after password check) ─────────────
-- Returns true if the operator chose to quit to the shell.
local function adminLoop()
    while true do
        local cfg = loadCfg()
        header(cfg.shop_name .. " -- Admin")
        print("  Address : " .. api.getShopAddr():sub(1, 24) .. "...")
        print("  (send AMI to '" .. cfg.shop_name .. "' to fund sells)")
        print(string.format("  Reserve : %.4f AMI", api.getShopBal() / 1000000))
        say(cfg.verified and colors.green or colors.red,
            "  Safety test: " .. (cfg.verified and "passed" or "NOT passed"))
        print("")
        print("  [T]  Run safety test")
        print("  [N]  Node manager")
        print(string.format("  [R]  Rate        (%d uAMI per coin)", cfg.rate))
        print(string.format("  [M]  Max trade   (%d coins)", cfg.max_coins))
        print(string.format("  [D]  Distance    (%d blocks)", cfg.radius))
        print("  [L]  Log   [U]  Self-update   [Q]  Quit to shell")
        print("  [B]  Back to the exchange")
        local key = menuKey()

        if key == "b" then
            return false

        elseif key == "t" then
            safetyTest()

        elseif key == "n" then
            nodeManager()

        elseif key == "r" then
            header("Rate")
            local r = tonumber(ask("  uAMI per coin: "))
            if r and r >= 1 and r == math.floor(r) then
                cfg.rate = r; saveCfg(cfg); print("  Saved.")
            else
                print("  Unchanged.")
            end
            os.sleep(0.8)

        elseif key == "m" then
            header("Max trade")
            local m = tonumber(ask("  Max coins per trade: "))
            if m and m >= 1 and m == math.floor(m) then
                cfg.max_coins = m; saveCfg(cfg); print("  Saved.")
            else
                print("  Unchanged.")
            end
            os.sleep(0.8)

        elseif key == "d" then
            header("Distance")
            print("  How close (in blocks, from the command block)")
            print("  a player must stand to count as 'at the exchange'.")
            local d = tonumber(ask("  Blocks (3-32): "))
            if d and d >= 3 and d <= 32 and d == math.floor(d) then
                cfg.radius = d; saveCfg(cfg); print("  Saved.")
            else
                print("  Unchanged.")
            end
            os.sleep(0.8)

        elseif key == "l" then
            showLog()

        elseif key == "u" then
            selfUpdate()
            -- only returns on failure; on success it reboots

        elseif key == "q" then
            return true
        end
        drawBoard()
    end
end

-- ── Keyboard input loop ────────────────────────────────────────────────────────
-- Admin access: press GRAVE (`) -- not shown in the public menu.
local function inputLoop()
    while true do
        printMenu()
        local key = menuKey()

        -- GRAVE (`) -- hidden admin trigger
        if key == "`" then
            header("Access required.")
            io.write("  Password: ")
            local inp = read("*")
            inp = (inp or ""):gsub("%s", "")
            if #inp > 0 and api.checkAdminPass(inp) then
                if adminLoop() then
                    term.clear(); term.setCursorPos(1, 1)
                    print("Ami Exchange stopped.")
                    return
                end
            else
                say(colors.red, "  Access denied.")
                os.sleep(1)
            end

        -- [B] -- buy coins with AMI
        elseif key == "b" and api.isOpen() then
            buyFlow()

        -- [S] -- sell coins for AMI
        elseif key == "s" and api.isOpen() then
            sellFlow()
        end
    end
end

-- ── Boot sequence ─────────────────────────────────────────────────────────────
term.clear(); term.setCursorPos(1, 1)
print("============================================")
print("  The Great Ami Exchange v1.0  --  Boot")
print("============================================")
print("")
print("Initialising peripherals...")

lockDown()
local shopAddr = api.init()

print("  Address       : " .. shopAddr:sub(1, 16) .. "...")
print("  Monitor       : " .. (api.getMonitor() and "TOP [OK]" or "TOP [--] (optional)"))
print("  Modem         : " .. (api.getModem() and "[OK]" or "[MISSING]"))
print("  Command block : " .. (api.hasCommands() and "[OK]" or "[MISSING]"))
print("")

-- Password setup: if no admin password is saved, prompt to create one now.
if not api.hasAdminPass() then
    print("============================================")
    print("  First-Run Setup: Set Admin Password")
    print("============================================")
    print("")
    print("No admin password is set. Create one now.")
    print("(This is used to unlock the admin panel.)")
    print("")
    local pw1, pw2
    repeat
        io.write("New password: ")
        pw1 = read("*")
        if #pw1 < 4 then
            print("Too short -- minimum 4 characters.")
        else
            io.write("Confirm password: ")
            pw2 = read("*")
            if pw1 ~= pw2 then
                print("Passwords do not match, try again.")
                pw1 = nil
            end
        end
    until pw1 and pw1 == pw2
    api.setAdminPass(pw1)
    term.setTextColor(colors.green)
    print("Password saved.")
    term.setTextColor(colors.white)
    print("")
    print("Next: press ` (backtick) on the main screen, add a")
    print("node, then run the safety test to open trading.")
    print("")
end

print("Starting in 3 seconds...")
os.sleep(3)

ui.init(api.getMonitor())
drawBoard()

-- If inputLoop returns (admin chose Quit), the sync loop is killed with it.
-- A crash must not leave a shell open next to the command block: reboot.
local ok, err = pcall(parallel.waitForAny, inputLoop, syncLoop)
if not ok then
    api.log("ERROR", "startup", "crashed: " .. tostring(err))
    term.setTextColor(colors.red)
    print("Ami Exchange crashed -- rebooting in 5 seconds.")
    print(tostring(err))
    os.sleep(5)
    os.reboot()
end
