#!/usr/bin/env python3
"""Pre-render the AmiCoin cooling fan into static frames using CC:Tweaked's
2x3 "teletext" block glyphs (codes 128-159).

WHY: CC:Tweaked's font is NOT CP437 - codes like 219/178/177/176 (full/shade)
render as garbage. The only real drawing glyphs are the 2x3 sextant blocks at
128-159. Each char cell is a 2-wide x 3-tall grid of sub-pixels:

    TL(1)  TR(2)
    ML(4)  MR(8)
    BL(16) BR(via colour-swap)

    code = 128 + TL*1 + TR*2 + ML*4 + MR*8 + BL*16

The bottom-right sub-pixel is normally done by swapping fg/bg; to keep each frame
a single-colour row-string (cheap mon.write) we render only the 5 directly-
addressable sub-pixels (BR off). This still DOUBLES horizontal and TRIPLES
vertical resolution vs one glyph/cell, so the fan looks smooth.

Output: ami/lib/ui/widgets/fan_frames.lua  (Lua \\ddd decimal escapes)
Runtime blits one row-string per line in a single colour. Zero trig at runtime.
"""
import math

COLS, ROWS = 17, 9              # character dimensions (unchanged)
SX, SY = 2, 3                   # sub-pixels per char cell
GW, GH = COLS * SX, ROWS * SY   # 34 x 27 sub-pixel grid

BLADES = 4
FRAMES = 8                      # one seamless loop (rotation sweeps 2*pi/BLADES)

CXp = (GW - 1) / 2.0
CYp = (GH - 1) / 2.0
R = min(CXp, CYp) - 0.5         # disc radius in sub-pixels


def blade_on(px, py, rotation):
    """Is this sub-pixel part of a fan blade?"""
    dx = px - CXp
    dy = py - CYp
    dist = math.sqrt(dx * dx + dy * dy)
    if dist > R:
        return False
    if dist < R * 0.12:
        return True                      # solid hub
    ang = math.atan2(dy, dx)
    s = math.sin(BLADES * ang + 0.25 * dist + rotation)
    return s > 0.0                       # blade vs gap


def build_frame(rotation):
    sub = [[blade_on(x, y, rotation) for x in range(GW)] for y in range(GH)]
    rows = []
    for cy in range(ROWS):
        codes = []
        for cx in range(COLS):
            x0, y0 = cx * SX, cy * SY
            tl = sub[y0 + 0][x0 + 0]
            tr = sub[y0 + 0][x0 + 1]
            ml = sub[y0 + 1][x0 + 0]
            mr = sub[y0 + 1][x0 + 1]
            bl = sub[y0 + 2][x0 + 0]
            # br omitted (needs colour-swap); single-colour frames.
            bits = (1 if tl else 0) | (2 if tr else 0) | (4 if ml else 0) \
                 | (8 if mr else 0) | (16 if bl else 0)
            codes.append(128 + bits)
        rows.append("".join("\\%03d" % c for c in codes))
    return rows


def main():
    frames = [build_frame(i * (2 * math.pi / BLADES) / FRAMES) for i in range(FRAMES)]

    out = [
        "-- ami/lib/ui/widgets/fan_frames.lua",
        "-- AUTO-GENERATED by tools/gen_fan_frames.py - do not edit by hand.",
        "-- CC:Tweaked 2x3 teletext blocks (codes 128-159): %d frames, %dx%d chars"
        % (FRAMES, COLS, ROWS),
        "-- (effective %dx%d sub-pixels). Blit one row-string per line, single colour."
        % (GW, GH),
        "return {",
        "  cols = %d," % COLS,
        "  rows = %d," % ROWS,
        "  frames = {",
    ]
    for f in frames:
        out.append("    {")
        for r in f:
            out.append('      "%s",' % r)
        out.append("    },")
    out += ["  },", "}", ""]

    path = "ami/lib/ui/widgets/fan_frames.lua"
    with open(path, "w") as fh:
        fh.write("\n".join(out))
    print("Wrote %s (%d frames, %dx%d chars, %dx%d sub-pixels)"
          % (path, FRAMES, COLS, ROWS, GW, GH))


if __name__ == "__main__":
    main()

    main()
