#!/usr/bin/env python3
"""Generate ami/lib/ui/manifest.txt — the full list of UI files to ship.

Installers (installnode/installpad/installshop) and the in-node self-update read
this manifest and download EVERY listed file, so the whole Opus UI tree ships and
self-update stays complete without anyone hand-editing file lists. Run this after
adding/removing any file under ami/lib/ui/.

Usage: python3 tools/gen_ui_manifest.py
"""
import os
import fnmatch

ROOT = os.path.join(os.path.dirname(__file__), "..")
UI_DIR = os.path.join(ROOT, "ami", "lib", "ui")
MANIFEST = os.path.join(UI_DIR, "manifest.txt")

# Dev-only files we never ship (demos, examples, ad-hoc verify scripts).
EXCLUDE = [
    "*_demo.lua", "*_demo2.lua", "_demo.lua", "_demo2.lua",
    "*_verify_*.lua", "_verify_stage1.lua",
    "*_example.lua", "*integration_example.lua",
    "manifest.txt",
]


def excluded(name):
    return any(fnmatch.fnmatch(name, pat) for pat in EXCLUDE)


def main():
    paths = []
    for dirpath, _dirs, files in os.walk(UI_DIR):
        for f in sorted(files):
            if not f.endswith(".lua"):
                continue
            if excluded(f):
                continue
            full = os.path.join(dirpath, f)
            rel = "/" + os.path.relpath(full, ROOT).replace(os.sep, "/")
            paths.append(rel)
    paths.sort()

    header = [
        "# ami/lib/ui manifest - AUTO-GENERATED by tools/gen_ui_manifest.py",
        "# One repo-relative path per line. Installers + self-update ship all of these.",
        "# Regenerate after adding/removing any ami/lib/ui file.",
    ]
    with open(MANIFEST, "w") as fh:
        fh.write("\n".join(header) + "\n")
        fh.write("\n".join(paths) + "\n")
    print("Wrote %s (%d files)" % (MANIFEST, len(paths)))
    for p in paths:
        print("  " + p)


if __name__ == "__main__":
    main()
